### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by fkorotkov** [hashicorp/nomad-skeleton-driver-plugin#20]
Hello there,

Is there a particular reason for the template being under `[MPL-2.0 license](https://github.com/hashicorp/nomad-skeleton-driver-plugin/blob/main/LICENSE)` license? Could it be changed to MIT?

I see why [Nomad](https://github.com/hashicorp/nomad) itself and [Go  Plugin SDK](https://github.com/hashicorp/go-plugin) are under `MPL-2.0`. In case of this repository it seems a bit forcing since code here suppose to be used as a starting point and **will be changed a lot** during development.

With this issue I'd like to raise the concern and kindly ask to consider changing the License to MIT.

**Comment by mmcquillan** [comment]
Thank you for the feedback. HashiCorp has been uniform in the use of the MPL-2.0 license. I'll pass this along to our legal team for future consideration.

**Comment by fkorotkov** [comment]
I personally consider such examples more like documentation and usually examples from documentation don't obligate you to open source code you used it in.

Thank you for the quick response and passing it to the team! 🙌
