### ISSUE TITLE
Build error on fresh git clone on Windows

### ISSUE THREAD

**Issue by jpvillaseca** [hashicorp/nomad-skeleton-driver-plugin#25]
After checking out the skeleton template and running `make build`, there's a build error on Windows

```sh
> make build
go build -o hello-driver .
# github.com/hashicorp/nomad/client/lib/fifo
..\..\..\pkg\mod\github.com\hashicorp\nomad@v1.4.2\client\lib\fifo\fifo_windows.go:98:18: undefined: winio.ListenOnlyPipe
make: *** [GNUmakefile:11: build] Error 1
```

I'm running:
go version go1.20 windows/amd64
Windows 11 (Version 10.0.22621 Build 22621)

**Comment by shoenig** [comment]
Hi @jpvillaseca! Can you try adding this `replace` statement copied from Nomad's `go.mod` file?

https://github.com/hashicorp/nomad/blob/main/go.mod#L7

I _suspect_ that should fix it but I haven't tried myself

**Comment by jpvillaseca** [comment]
hey man, it solves the issue :) 
thanks.
