### ISSUE TITLE
Depends on Nomad APIs which use vendored types

### ISSUE THREAD

**Issue by benbuzbee** [hashicorp/nomad-skeleton-driver-plugin#4]
Disclaimer: I don't know anything about go but I do know about software here's how trying to use this went for me :) please correct me if I missed an obvious thing that people who know about go know
```
bbuzbee@bbuzbee-dev:/tmp/sandbox$ GOPATH=/tmp/sandbox go get github.com/hashicorp/nomad-skeleton-driver-plugin
```

```
# github.com/hashicorp/nomad-skeleton-driver-plugin/hello
src/github.com/hashicorp/nomad-skeleton-driver-plugin/hello/driver.go:193:37: cannot use logger (type "github.com/hashicorp/go-hclog".Logger) as type "github.com/hashicorp/nomad/vendor/github.com/hashicorp/go-hclog".Logger in argument to eventer.NewEventer:
	"github.com/hashicorp/go-hclog".Logger does not implement "github.com/hashicorp/nomad/vendor/github.com/hashicorp/go-hclog".Logger (wrong type for Named method)
		have Named(string) "github.com/hashicorp/go-hclog".Logger

... more of the same ...
```
Parsing this (and learning about go package management) it seems this project (the skeleton driver)  is trying to import some APIs from the nomad package (in this example, it is using eventer.NewEventer from [eventer.go](https://github.com/hashicorp/nomad/blob/8d173664cbcf85b18b502b11541aa605962e92f3/drivers/shared/eventer/eventer.go#L52))

That signature requires an [hclog.Logger](https://github.com/hashicorp/go-hclog) but that type is [vendored](https://github.com/hashicorp/nomad/blob/8d173664cbcf85b18b502b11541aa605962e92f3/vendor/vendor.json#L239) so the full type paths are different.

So now to get past this I have to delete the vendored type from nomad so it resolves to the un-versioned type.  

```
$ rm -rf /tmp/sandbox/src/github.com/hashicorp/nomad/vendor/github.com/hashicorp/go-hclog/ && cd /tmp/sandbox/src/github.com/hashicorp/nomad-skeleton-driver-plugin && GOPATH=/tmp/sandbox go build
# github.com/hashicorp/nomad-skeleton-driver-plugin/hello
hello/driver.go:397:3: cannot use pluginClient (type *"github.com/hashicorp/nomad/vendor/github.com/hashicorp/go-plugin".Client) as type *"github.com/hashicorp/go-plugin".Client in field value
```

On to the next...
```
$ rm -rf /tmp/sandbox/src/github.com/hashicorp/nomad/vendor/github.com/hashicorp/go-plugin/ && cd /tmp/sandbox/src/github.com/hashicorp/nomad-skeleton-driver-plugin && GOPATH=/tmp/sandbox go build
# github.com/hashicorp/nomad/plugins/drivers
../nomad/plugins/drivers/plugin.go:14:5: cannot use &PluginDriver literal (type *PluginDriver) as type "github.com/hashicorp/go-plugin".GRPCPlugin in assignment:
	*PluginDriver does not implement "github.com/hashicorp/go-plugin".GRPCPlugin (wrong type for GRPCClient method)

```
One more for success
```
$ rm -rf /tmp/sandbox/src/github.com/hashicorp/nomad/vendor/google.golang.org/grpc && cd /tmp/sandbox/src/github.com/hashicorp/nomad-skeleton-driver-plugin && GOPATH=/tmp/sandbox go build
```

Yay.
```
$ ls
config  go.mod  go.sum  hello  LICENSE  main.go  nomad-skeleton-driver-plugin  README.md
```

If the recommendation for drivers is that they depend on these APIs in nomad, then I believe nomad should not be vendoring these types. Am I missing something? Thanks!

Housekeeping:
```
bbuzbee@bbuzbee-dev:/tmp/sandbox$ go version
go version go1.12.9 linux/amd64
```

**Comment by benbuzbee** [comment]
@lgfa29 this may be on my end.

I think module mode wasn't being used in go. GO111MODULE=on to force this I believe fixes it, presumably by making the entire tree use the pkg installation

**Comment by lgfa29** [comment]
Thanks for the follow-up @benbuzbee.

I was able to reproduce the error you saw with a clean `GOPATH`. Strangely, even though `go get` fails `go build` works fine so you should be able to develop your plug-in despite of this.

Setting `GO111MODULE=on` shouldn't be necessary, but since that fixed the problem for you I will have to revisit this assumption and update the documentation accordingly.

I will get back you once I have more information.

**Comment by lgfa29** [comment]
Hi @benbuzbee. 

We fixed our dependencies and updated the project's `README` to better explain how to use it. You were right about `GO111MODULE`, it needs to be set to `GO111MODULE=on` (or `GO111MODULE=auto` if you are working outside your `GOPATH`) in order for things to work properly.

Unfortunately there's no direct way to pull updates from this template into your repository, so you will need to manually apply [these changes](https://github.com/hashicorp/nomad-skeleton-driver-plugin/compare/9ac058a9457ea0ea6bc987cdb902bf6195e63e94...18790a2b82fa3e7cdc04f1d73f566656f7b93b49#diff-37aff102a57d3d7b797f152915a6dc16) to your `go.mod` file and follow the new `README` instructions. If you still run into problems try applying the changes in `go.sum` as well, or, if you haven't started working in your plugin yet, generate a new repository with the latest template.

Let us know if none of these work for you.

**Comment by benbuzbee** [comment]
Thank you @lgfa29, appreciated the quick and direct responses. I am unblocked and happy to have left the repo in ever so slightly better state :)
